Dolittle.namespace("Dolittle.validation");
Dolittle.Exception.define("Dolittle.validation.OptionsNotDefined", "Option was undefined");
Dolittle.Exception.define("Dolittle.validation.OptionsValueNotSpecified", "Required value in Options is not specified. ");
Dolittle.Exception.define("Dolittle.validation.NotANumber", "Value is not a number");
Dolittle.Exception.define("Dolittle.validation.NotAString", "Value is not a string");
Dolittle.Exception.define("Dolittle.validation.ValueNotSpecified","Value is not specified");
Dolittle.Exception.define("Dolittle.validation.MinNotSpecified","Min is not specified");
Dolittle.Exception.define("Dolittle.validation.MaxNotSpecified","Max is not specified");
Dolittle.Exception.define("Dolittle.validation.MinLengthNotSpecified","Min length is not specified");
Dolittle.Exception.define("Dolittle.validation.MaxLengthNotSpecified","Max length is not specified");
Dolittle.Exception.define("Dolittle.validation.MissingExpression","Expression is not specified");